import 'dart:io';

import 'settings_service.dart';
import 'ytdlp_options.dart';

/// Local Instagram session backed by a Netscape cookies.txt for yt-dlp.
class InstagramSession {
  InstagramSession(this.settings);

  final SettingsService settings;

  static const loginUrl = 'https://www.instagram.com/accounts/login/';
  static const homeUrl = 'https://www.instagram.com/';

  Future<bool> hasSession() async {
    final path = settings.cookiesPath;
    if (path == null || path.isEmpty) return false;
    final file = File(path);
    if (!await file.exists()) return false;
    try {
      final text = await file.readAsString();
      return text.contains('sessionid');
    } catch (_) {
      return false;
    }
  }

  /// Parses a Cookie header (`a=b; c=d`) into Netscape format and persists it.
  Future<String> saveFromCookieHeader(
    String cookieHeader, {
    String domain = '.instagram.com',
  }) async {
    final pairs = _parseCookieHeader(cookieHeader);
    if (!pairs.containsKey('sessionid') || pairs['sessionid']!.isEmpty) {
      throw StateError('Instagram session cookie (sessionid) not found yet.');
    }

    final destPath = await settings.cookiesStoragePath();
    final dest = File(destPath);
    await dest.parent.create(recursive: true);

    final buf = StringBuffer()
      ..writeln('# Netscape HTTP Cookie File')
      ..writeln('# Generated by Download Everything — stay on this device only.');

    final expiry = DateTime.now()
        .add(const Duration(days: 365))
        .millisecondsSinceEpoch ~/
        1000;

    for (final entry in pairs.entries) {
      buf.writeln(
        _netscapeLine(
          domain: domain,
          includeSubdomains: true,
          path: '/',
          secure: true,
          expiry: expiry,
          name: entry.key,
          value: entry.value,
        ),
      );
    }

    await dest.writeAsString(buf.toString(), flush: true);
    await settings.setCookiesPath(destPath);
    return destPath;
  }

  Future<void> clear() => settings.clearCookies();

  static Map<String, String> _parseCookieHeader(String header) {
    final out = <String, String>{};
    for (final part in header.split(';')) {
      final trimmed = part.trim();
      if (trimmed.isEmpty) continue;
      final eq = trimmed.indexOf('=');
      if (eq <= 0) continue;
      final name = trimmed.substring(0, eq).trim();
      final value = trimmed.substring(eq + 1).trim();
      if (name.isEmpty) continue;
      out[name] = value;
    }
    return out;
  }

  static String _netscapeLine({
    required String domain,
    required bool includeSubdomains,
    required String path,
    required bool secure,
    required int expiry,
    required String name,
    required String value,
  }) {
    return [
      domain,
      includeSubdomains ? 'TRUE' : 'FALSE',
      path,
      secure ? 'TRUE' : 'FALSE',
      '$expiry',
      name,
      value,
    ].join('\t');
  }
}

/// True when yt-dlp / Instagram indicated auth is required.
bool needsInstagramAuth(String? error) {
  if (error == null || error.isEmpty) return false;
  final lower = error.toLowerCase();
  return lower.contains('empty media') ||
      lower.contains('impersonat') ||
      lower.contains('login') ||
      lower.contains('cookie') ||
      lower.contains('private') ||
      lower.contains('not available') ||
      lower.contains('rate-limit');
}

/// Whether this URL should use the Instagram sign-in flow.
bool shouldUseInstagramSession(String url) => isInstagramUrl(url);
